import type { MetadataRoute } from "next";

// PWA manifest (App Router file convention). Colors track the default
// "midnight" theme (deep navy); icons come from public/icons, generated by
// scripts/gen-icons.mjs. purpose "any" only — the art has inner padding but
// isn't built for the maskable safe zone, so Android would crop it.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Mxologist",
    short_name: "Mxologist",
    description:
      "Find cocktails you can make with the bottles you already have.",
    start_url: "/",
    display: "standalone",
    background_color: "#0c1322",
    theme_color: "#0c1322",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
